#!/bin/bash

# Grab the working dir
cd $(dirname $0)
dir=$PWD
cd - > /dev/null

# ensure arg length is not zero or handle 'help'.  print helpful message
if [[ $# == 0 || $1 == "help" ]]; then
  echo "info:  make-project is a shell script that provides a convenient execution wrapper to the jCatapult Ant tools makeproject suite."
  echo "usage: make-project <ant target>"
  echo
  echo "executing 'ant -p' to display available makeproject ant targets..."
  echo
  ant -f ${dir}/build.xml -p
  exit
fi

ant -f ${dir}/build.xml $@
