#!/bin/bash

# Build up the deploy classpath
dir=$(dirname $0)
classpath=
for f in $(ls $dir/../lib); do
  classpath=$dir/../lib/$f:$classpath
done

java -cp $classpath org.jcatapult.deployment.DeploymentManager $1 ./ deploy/remote/deploy.xml
