#!/bin/bash

# Build up the scaffolding classpath
dir=$(dirname $0)
classpath=
for f in $(ls $dir/../lib); do
  classpath=$dir/../lib/$f:$classpath
done

deployConfigFile=deploy/remote/deploy.xml

java -cp $classpath -Ddeployer.home=$dir/.. \
  org.jcatapult.deployment.DeploymentManager $deployConfigFile
