//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.25 at 05:00:34 PM MDT 
//


package org.jcatapult.deployment.domain.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       
 * 
 * <p>Java class for environment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="environment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="homeDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fileDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="webDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dbName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dbUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dbPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environment", propOrder = {
    "homeDir",
    "workDir",
    "fileDir",
    "webDir",
    "dbName",
    "dbUsername",
    "dbPassword"
})
public class Environment {

    @XmlElement(required = true)
    protected String homeDir;
    @XmlElement(required = true)
    protected String workDir;
    @XmlElement(required = true)
    protected String fileDir;
    @XmlElement(required = true)
    protected String webDir;
    @XmlElement(required = true)
    protected String dbName;
    @XmlElement(required = true)
    protected String dbUsername;
    @XmlElement(required = true)
    protected String dbPassword;
    @XmlAttribute(required = true)
    protected String type;

    /**
     * Gets the value of the homeDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeDir() {
        return homeDir;
    }

    /**
     * Sets the value of the homeDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeDir(String value) {
        this.homeDir = value;
    }

    /**
     * Gets the value of the workDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkDir() {
        return workDir;
    }

    /**
     * Sets the value of the workDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkDir(String value) {
        this.workDir = value;
    }

    /**
     * Gets the value of the fileDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDir() {
        return fileDir;
    }

    /**
     * Sets the value of the fileDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDir(String value) {
        this.fileDir = value;
    }

    /**
     * Gets the value of the webDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebDir() {
        return webDir;
    }

    /**
     * Sets the value of the webDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebDir(String value) {
        this.webDir = value;
    }

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the dbUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbUsername() {
        return dbUsername;
    }

    /**
     * Sets the value of the dbUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbUsername(String value) {
        this.dbUsername = value;
    }

    /**
     * Gets the value of the dbPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * Sets the value of the dbPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbPassword(String value) {
        this.dbPassword = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
