//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.25 at 05:00:34 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jcatapult.org/schemas/deploy", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jcatapult.deployment.domain.jaxb;
