#!/bin/bash

# get args and count
args=("$@")
argsSize=${#args[@]}

# ensure ANT_HOME is defined in environment
if [ -z $ANT_HOME ]; then
  echo "Please set the ANT_HOME environment variable to the ant 1.7.* installation directory"
  exit
fi

# directory where the ant build script will be executed from
dir=$ANT_HOME/tools-jcatapult/makeproject

# ensure arg length is not zero or handle 'help'.  print helpful message
if [[ $argsSize -eq 0 || ${args[0]} = "help" ]]; then
  echo "info:  make-project is a shell script that provides a convenient execution wrapper to the jCatapult Ant tools makeproject suite."
  echo "usage: make-project <ant target>"
  echo
  echo "executing 'ant -p' to display available makeproject ant targets..."
  echo
  ant -f ${dir}/build.xml -p
  exit
fi

ant -f ${dir}/build.xml $@
